# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"
 
      - name: Install Gradle 8.2.1
        run: |
          wget https://services.gradle.org/distributions/gradle-8.2.1-bin.zip
          unzip gradle-8.2.1-bin.zip
          echo "${PWD}/gradle-8.2.1/bin" >> $GITHUB_PATH
      - name: Grant execute permission for gradlew
        run: chmod +x ./backend/bugbusters/gradlew
 
      - name: Run Tests with Gradle
        working-directory: ./project/PolyPlotter
        run: ./gradlew test -Dspring.profiles.active=test

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            project/PolyPlotter/build/libs/*.jar
